name: 'Python CodeArtifact Configuration'
description: 'Outputs variables necessary for pip and twine repository configuration.'
inputs:
  aws-account-id:
    description: 'Your AWS Account ID'
    required: true
  codeartifact-domain:
    description: 'Your CodeArtifact domain'
    required: true
  codeartifact-repo:
    description: 'CodeArtifact repository you want to use.'
  auth-token-duration:
    description: 'Duration of authentication token used in generated URLs.'
    default: 1800
outputs:
  pip-index-url:
    description: 'Store this value in PIP_INDEX_URL environment variable for steps which use pip.'
    value: ${{ steps.get-codeartifact-details.outputs.pip-index-url }}
  twine-username:
    description: 'Store this value in TWINE_USERNAME environment variable for steps which use twine.'
    value: ${{ steps.get-codeartifact-details.outputs.twine-username }}
  twine-password:
    description: 'Store this value in TWINE_PASSWORD environment variable for steps which use twine.'
    value: ${{ steps.get-codeartifact-details.outputs.twine-password }}
  twine-repository-url:
    description: 'Store this value in TWINE_REPOSITORY_URL environment variable for steps which use twine.'
    value: ${{ steps.get-codeartifact-details.outputs.twine-repository-url }}
runs:
  using: "composite"
  steps:
    - id: get-codeartifact-details
      run: |
        CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain ${{ inputs.codeartifact-domain }} --domain-owner ${{ inputs.aws-account-id }} --query authorizationToken --output text --duration-seconds ${{ inputs.auth-token-duration }})
        echo "::set-output name=pip-index-url::https://aws:${CODEARTIFACT_AUTH_TOKEN}@${{ inputs.codeartifact-domain }}-${{ inputs.aws-account-id }}.d.codeartifact.${AWS_DEFAULT_REGION}.amazonaws.com/pypi/${{ inputs.codeartifact-repo }}/simple/"
        echo "::set-output name=twine-username::aws"
        echo "::set-output name=twine-password::${CODEARTIFACT_AUTH_TOKEN}"
        echo "::set-output name=twine-repository-url::$(aws codeartifact get-repository-endpoint --domain ${{ inputs.codeartifact-domain }} --domain-owner ${{ inputs.aws-account-id }} --repository ${{ inputs.codeartifact-repo }} --format pypi --query repositoryEndpoint --output text)"
      shell: bash
